[package]
name = "luna_ce"
version = "1.0.0"
authors = ["Daniele"]
edition = "2026"

[dependencies]
rand = "0.8"
rand_chacha = "0.3"  
log = "0.4"          
env_logger = "0.11"  

[features]
default = []
simd = []
nnue = []
embedded_nnue = []
evaluation = []  # Feature flag per evaluation

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
